// Barrel cho lớp service. Import gọn: import { monHocService } from '../services'
export * as monHocService from './monHocService'
export * as baiGiangService from './baiGiangService'
export * as danhGiaService from './danhGiaService'
export * as hocPhanMonHocService from './hocPhanMonHocService'
export * as sinhVienService from './sinhVienService'
export * as luuTruService from './luuTruService'
export * as lichSuService from './lichSuService'
export * as nguoiDungService from './nguoiDungService'
